
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CAR CDR CONS DIV INT LET LPAREN MINUS PLUS RPAREN SEMI TIMES VARlispStart : lisp SEMIlispStart : list SEMIlisp : INTlisp : VARlisp : LPAREN PLUS lisp lisp RPARENlisp : LPAREN MINUS lisp lisp RPARENlisp : LPAREN TIMES lisp lisp RPARENlisp : LPAREN DIV lisp lisp RPARENlisp : LPAREN CAR list RPARENlisp : LPAREN LET LPAREN varlist RPAREN lisp RPARENvarlist : LPAREN VAR lisp RPARENvarlist : LPAREN VAR lisp RPAREN varlistlist : LPAREN CDR list RPARENlist : LPAREN seq RPARENlist : LPAREN CONS lisp list RPARENseq : seq : lisp seq'
    
_lr_action_items = {'INT':([0,4,5,6,10,11,12,13,14,19,20,22,23,24,25,35,40,41,42,43,44,45,50,],[4,-3,-4,4,4,4,4,4,4,4,4,4,4,4,4,-9,-5,-6,-7,-8,4,4,-10,]),'VAR':([0,4,5,6,10,11,12,13,14,19,20,22,23,24,25,35,36,40,41,42,43,44,45,50,],[5,-3,-4,5,5,5,5,5,5,5,5,5,5,5,5,-9,44,-5,-6,-7,-8,5,5,-10,]),'LPAREN':([0,4,5,6,10,11,12,13,14,15,16,17,19,20,22,23,24,25,27,30,35,40,41,42,43,44,45,49,50,],[6,-3,-4,9,9,9,9,9,9,25,27,25,9,9,9,9,9,9,36,25,-9,-5,-6,-7,-8,9,9,36,-10,]),'$end':([1,7,8,],[0,-1,-2,]),'SEMI':([2,3,4,5,29,35,38,40,41,42,43,46,50,],[7,8,-3,-4,-14,-9,-13,-5,-6,-7,-8,-15,-10,]),'RPAREN':([4,5,6,11,18,21,25,26,28,29,31,32,33,34,35,37,38,39,40,41,42,43,46,47,48,49,50,51,],[-3,-4,-16,-16,29,-17,-16,35,38,-14,40,41,42,43,-9,45,-13,46,-5,-6,-7,-8,-15,49,50,-11,-10,-12,]),'PLUS':([6,9,],[10,10,]),'MINUS':([6,9,],[12,12,]),'TIMES':([6,9,],[13,13,]),'DIV':([6,9,],[14,14,]),'CAR':([6,9,],[15,15,]),'LET':([6,9,],[16,16,]),'CDR':([6,25,],[17,17,]),'CONS':([6,25,],[19,19,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'lispStart':([0,],[1,]),'lisp':([0,6,10,11,12,13,14,19,20,22,23,24,25,44,45,],[2,11,20,11,22,23,24,30,31,32,33,34,11,47,48,]),'list':([0,15,17,30,],[3,26,28,39,]),'seq':([6,11,25,],[18,21,18,]),'varlist':([27,49,],[37,51,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> lispStart","S'",1,None,None,None),
  ('lispStart -> lisp SEMI','lispStart',2,'p_lispStart','LispParser.py',5),
  ('lispStart -> list SEMI','lispStart',2,'p_lispStart_1','LispParser.py',8),
  ('lisp -> INT','lisp',1,'p_lisp_1','LispParser.py',13),
  ('lisp -> VAR','lisp',1,'p_lisp_2','LispParser.py',16),
  ('lisp -> LPAREN PLUS lisp lisp RPAREN','lisp',5,'p_lisp_3','LispParser.py',19),
  ('lisp -> LPAREN MINUS lisp lisp RPAREN','lisp',5,'p_lisp_4','LispParser.py',22),
  ('lisp -> LPAREN TIMES lisp lisp RPAREN','lisp',5,'p_lisp_5','LispParser.py',25),
  ('lisp -> LPAREN DIV lisp lisp RPAREN','lisp',5,'p_lisp_6','LispParser.py',28),
  ('lisp -> LPAREN CAR list RPAREN','lisp',4,'p_lisp_7','LispParser.py',31),
  ('lisp -> LPAREN LET LPAREN varlist RPAREN lisp RPAREN','lisp',7,'p_lisp_8','LispParser.py',34),
  ('varlist -> LPAREN VAR lisp RPAREN','varlist',4,'p_varlist','LispParser.py',39),
  ('varlist -> LPAREN VAR lisp RPAREN varlist','varlist',5,'p_varlist_1','LispParser.py',42),
  ('list -> LPAREN CDR list RPAREN','list',4,'p_list_1','LispParser.py',46),
  ('list -> LPAREN seq RPAREN','list',3,'p_list_2','LispParser.py',49),
  ('list -> LPAREN CONS lisp list RPAREN','list',5,'p_list_3','LispParser.py',52),
  ('seq -> <empty>','seq',0,'p_seq_1','LispParser.py',56),
  ('seq -> lisp seq','seq',2,'p_seq_2','LispParser.py',59),
]
